/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.VehiExpense.visao;

/**
 *
 * @author aluno
 */
public class TelaCategoriaDeGastos extends javax.swing.JPanel {

    /**
     * Creates new form TelaCategoriaDeGastos
     */
    public TelaCategoriaDeGastos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButtonCadastroPJ = new javax.swing.JButton();
        jButtonCadastoPF = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButtonCadastroPJ1 = new javax.swing.JButton();
        jButtonCadastroPJ2 = new javax.swing.JButton();
        jButtonCadastroPJ3 = new javax.swing.JButton();
        jButtonCadastroPJ4 = new javax.swing.JButton();

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Categoria de Gastos");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jButtonCadastroPJ.setBackground(new java.awt.Color(204, 204, 204));
        jButtonCadastroPJ.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jButtonCadastroPJ.setForeground(new java.awt.Color(0, 0, 0));
        jButtonCadastroPJ.setText("Manutenção");
        jButtonCadastroPJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastroPJActionPerformed(evt);
            }
        });

        jButtonCadastoPF.setBackground(new java.awt.Color(204, 204, 204));
        jButtonCadastoPF.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jButtonCadastoPF.setForeground(new java.awt.Color(0, 0, 0));
        jButtonCadastoPF.setText("Combustível");
        jButtonCadastoPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastoPFActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/VehiExpense/imagens/logo_arc_nova-removebg-preview (1).png"))); // NOI18N

        jButtonCadastroPJ1.setBackground(new java.awt.Color(204, 204, 204));
        jButtonCadastroPJ1.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jButtonCadastroPJ1.setForeground(new java.awt.Color(0, 0, 0));
        jButtonCadastroPJ1.setText("Limpeza");
        jButtonCadastroPJ1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastroPJ1ActionPerformed(evt);
            }
        });

        jButtonCadastroPJ2.setBackground(new java.awt.Color(204, 204, 204));
        jButtonCadastroPJ2.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jButtonCadastroPJ2.setForeground(new java.awt.Color(0, 0, 0));
        jButtonCadastroPJ2.setText("Licenciamento");
        jButtonCadastroPJ2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastroPJ2ActionPerformed(evt);
            }
        });

        jButtonCadastroPJ3.setBackground(new java.awt.Color(204, 204, 204));
        jButtonCadastroPJ3.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jButtonCadastroPJ3.setForeground(new java.awt.Color(0, 0, 0));
        jButtonCadastroPJ3.setText("Seguro");
        jButtonCadastroPJ3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastroPJ3ActionPerformed(evt);
            }
        });

        jButtonCadastroPJ4.setBackground(new java.awt.Color(204, 204, 204));
        jButtonCadastroPJ4.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jButtonCadastroPJ4.setForeground(new java.awt.Color(0, 0, 0));
        jButtonCadastroPJ4.setText("Eventuais");
        jButtonCadastroPJ4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastroPJ4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonCadastoPF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonCadastroPJ, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonCadastroPJ1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonCadastroPJ2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonCadastroPJ3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonCadastroPJ4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(321, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(327, 327, 327))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jButtonCadastoPF, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonCadastroPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonCadastroPJ1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonCadastroPJ2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonCadastroPJ3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonCadastroPJ4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCadastroPJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastroPJActionPerformed
        // TODO add your handling code here:
        TelaCadastroProprietarioPJ frame =new TelaCadastroProprietarioPJ();
        frame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonCadastroPJActionPerformed

    private void jButtonCadastoPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastoPFActionPerformed
        // TODO add your handling code here:
        TelaCadastroProprietarioPF frame = new TelaCadastroProprietarioPF();
        frame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonCadastoPFActionPerformed

    private void jButtonCadastroPJ1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastroPJ1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCadastroPJ1ActionPerformed

    private void jButtonCadastroPJ2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastroPJ2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCadastroPJ2ActionPerformed

    private void jButtonCadastroPJ3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastroPJ3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCadastroPJ3ActionPerformed

    private void jButtonCadastroPJ4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastroPJ4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCadastroPJ4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCadastoPF;
    private javax.swing.JButton jButtonCadastroPJ;
    private javax.swing.JButton jButtonCadastroPJ1;
    private javax.swing.JButton jButtonCadastroPJ2;
    private javax.swing.JButton jButtonCadastroPJ3;
    private javax.swing.JButton jButtonCadastroPJ4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
